apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: tenants.tenancy.x-k8s.io
spec:
  group: tenancy.x-k8s.io
  names:
    kind: Tenant
    plural: tenants
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            requireNamespacePrefix:
              description: If set to True, all the namespaces belong to the tenant
                are required to have TenantAdminNamespaceName as name prefix. By default,
                namespace prefix is not required.
              type: boolean
            tenantAdminNamespaceName:
              description: The name of tenant administration namespace, which is used
                to create all tenant related policy objects and custom resources.
              type: string
            tenantAdmins:
              description: TenantAdmins are the identities with admin privilege for
                tenant resources.
              items:
                type: object
              type: array
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []